#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/activerecord_graph_extractor'
require_relative '../lib/activerecord_graph_extractor/cli'

ActiveRecordGraphExtractor::CLI.start(ARGV) 